"""worker credentials and job ownership

Aditya Phase 2 (Worker Identity, Authorization Binding, and Security Audit
Completion): replaces the temporary `WORKER_SHARED_SECRET` boundary with
revocable, per-worker service identities.

Adds `worker_credentials` (owned by `app/modules/access_control/`, the same
module that owns `users`/`cases`/`case_memberships`/`auth_sessions`/
`security_audit_events`) -- one row per provisioned worker, storing only a
cryptographic digest of its credential, never the plaintext token. Also
adds a nullable `worker_jobs.claimed_by_worker_id` column (owned by
`app/modules/evidence_lifecycle/`) so a successful claim durably records
*which* authenticated worker identity currently owns a running job -- see
`docs/architecture/worker-identity-and-security.md`.

Hand-written, not autogenerated, same convention as every prior migration
in this repository: `app/modules/access_control/repository.py` and
`app/modules/evidence_lifecycle/repository.py` each define their own
SQLAlchemy Core `Table` objects matching these columns; `migrations/env.py`
keeps `target_metadata = None`.

Purely additive: one new table, one new column, one new foreign key. No
existing column, table, or constraint is modified or removed. A `worker_jobs`
row claimed before this migration (`claimed_by_worker_id IS NULL`) is not
retroactively attributed to any worker identity -- it simply becomes
unclaimable-by-identity until its lease expires and a real authenticated
worker reclaims it under the new system (see
`docs/architecture/worker-identity-and-security.md`'s migration note).

Revision ID: 48e9e76153ca
Revises: af5b05e61b08
Create Date: 2026-09-11

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "48e9e76153ca"
down_revision: str | None = "af5b05e61b08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_WORKER_CREDENTIAL_STATUSES = ("active", "revoked")


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "worker_credentials",
        sa.Column("worker_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        # A JSON array of processor-name strings, the same JSONB convention
        # already used for `security_audit_events.metadata_safe_json` and
        # `worker_results.derived_artifacts` -- not a Postgres native array
        # type, to keep exactly one "structured list column" pattern across
        # this repository's tables.
        sa.Column("allowed_processor_names", postgresql.JSONB(), nullable=False),
        # HMAC-SHA256(pepper, token) hex digest (or plain SHA-256 hex when no
        # pepper is configured, e.g. local development) -- never the
        # plaintext token. Unique so a digest collision (accidental reuse,
        # not a cryptographic break) is caught by the database, not silently
        # accepted.
        sa.Column("credential_digest", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("credential_digest", name="uq_worker_credentials_credential_digest"),
        sa.CheckConstraint(
            _check_in("status", _WORKER_CREDENTIAL_STATUSES), name="ck_worker_credentials_status"
        ),
    )
    # Supports `require_worker_principal`'s per-request digest lookup, which
    # every single call to an internal worker endpoint performs.
    op.create_index(
        "ix_worker_credentials_credential_digest", "worker_credentials", ["credential_digest"]
    )

    op.add_column(
        "worker_jobs",
        sa.Column(
            "claimed_by_worker_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("worker_credentials.worker_id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    # Supports the authorization check every `/result` and `/input` request
    # makes ("is the caller the worker identity currently bound to this job").
    op.create_index("ix_worker_jobs_claimed_by_worker_id", "worker_jobs", ["claimed_by_worker_id"])


def downgrade() -> None:
    op.drop_index("ix_worker_jobs_claimed_by_worker_id", table_name="worker_jobs")
    op.drop_column("worker_jobs", "claimed_by_worker_id")
    op.drop_index("ix_worker_credentials_credential_digest", table_name="worker_credentials")
    op.drop_table("worker_credentials")
