"""access control foundation

Adds the five Phase 1 access-control tables: `users`, `cases`,
`case_memberships`, `auth_sessions`, `security_audit_events`. See
`docs/decisions/ADR-003-authentication-and-case-scoped-access-control.md`
for the reasoning behind the constraints below.

Hand-written, not autogenerated: `migrations/env.py` keeps
`target_metadata = None` (Nipun's baseline decision, left untouched here).
`app/modules/access_control/repository.py` defines its own SQLAlchemy Core
`Table` objects matching these columns for querying, rather than adding a
project-wide declarative ORM base.

Revision ID: 7e8499f34f29
Revises: 3e8cbaa07711
Create Date: 2026-09-10 16:14:07.749865

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e8499f34f29"
down_revision: str | None = "3e8cbaa07711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_CLEARANCE_LEVELS = ("restricted", "confidential", "secret")
_CASE_ROLES = ("case_owner", "case_manager", "investigator", "analyst", "reviewer", "viewer")
_CASE_STATUSES = ("open", "closed", "archived")
_AUDIT_OUTCOMES = ("success", "failure", "denied")


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email_normalized", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("email_normalized", name="uq_users_email_normalized"),
    )

    op.create_table(
        "cases",
        sa.Column("case_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("case_reference", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("case_reference", name="uq_cases_case_reference"),
        sa.CheckConstraint(
            _check_in("classification", _CLEARANCE_LEVELS), name="ck_cases_classification"
        ),
        sa.CheckConstraint(_check_in("status", _CASE_STATUSES), name="ck_cases_status"),
    )

    op.create_table(
        "case_memberships",
        sa.Column("membership_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.user_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("clearance", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("case_id", "user_id", name="uq_case_memberships_case_user"),
        sa.CheckConstraint(_check_in("role", _CASE_ROLES), name="ck_case_memberships_role"),
        sa.CheckConstraint(
            _check_in("clearance", _CLEARANCE_LEVELS), name="ck_case_memberships_clearance"
        ),
    )
    op.create_index("ix_case_memberships_user_id", "case_memberships", ["user_id"])

    op.create_table(
        "auth_sessions",
        sa.Column("session_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.user_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column("token_family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "replaced_by_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("auth_sessions.session_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("refresh_token_hash", name="uq_auth_sessions_refresh_token_hash"),
    )
    op.create_index("ix_auth_sessions_user_id", "auth_sessions", ["user_id"])
    op.create_index("ix_auth_sessions_token_family_id", "auth_sessions", ["token_family_id"])

    op.create_table(
        "security_audit_events",
        sa.Column("event_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column(
            "user_id_nullable",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.user_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "case_id_nullable",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("ip_hash_or_safe_network_marker", sa.Text(), nullable=True),
        sa.Column(
            "metadata_safe_json",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.CheckConstraint(
            _check_in("outcome", _AUDIT_OUTCOMES), name="ck_security_audit_events_outcome"
        ),
    )
    op.create_index(
        "ix_security_audit_events_occurred_at", "security_audit_events", ["occurred_at"]
    )
    op.create_index(
        "ix_security_audit_events_user_id_nullable", "security_audit_events", ["user_id_nullable"]
    )
    op.create_index(
        "ix_security_audit_events_case_id_nullable", "security_audit_events", ["case_id_nullable"]
    )


def downgrade() -> None:
    op.drop_table("security_audit_events")
    op.drop_table("auth_sessions")
    op.drop_table("case_memberships")
    op.drop_table("cases")
    op.drop_table("users")
