"""graph projection jobs

Shreshtha Phase 2 (Canonical Observation-to-Neo4j Graph Projection): adds
the durable PostgreSQL projection queue/outbox that bridges an accepted
canonical `ObservationV1` (persisted by `app/modules/evidence_lifecycle/`'s
worker-result acceptance flow) to a case-scoped Neo4j graph projection.

`graph_projection_jobs` is defined in `app/modules/evidence_lifecycle/
repository.py` (`evidence_lifecycle/repository.py` inserts one row per
accepted observation, in the same transaction as `worker_results`/
`worker_observations` -- see `EvidenceLifecycleRepository.submit_result`),
because that module owns the transaction the row must be durable within.
`app/modules/graph/outbox_repository.py` imports that exact `Table` object
to read, claim, and transition rows -- a one-directional dependency
(`app.modules.graph` consumes `evidence_lifecycle`'s accepted results,
never the other way around; `evidence_lifecycle` never imports
`app.modules.graph` at all, see
`tests/security/evidence_lifecycle/test_evidence_lifecycle_boundaries.py`).

PostgreSQL remains the durable source of truth for "this observation needs
(re)projecting"; Neo4j itself is a derived, rebuildable projection -- a
Neo4j outage never discards an accepted worker result, it only leaves this
row retryable. See `docs/architecture/graph-projection.md`.

One row per canonical observation, enforced by a unique constraint on
`observation_id`: retries reuse the same row (`attempt` increments),
never a second row for the same observation.

Hand-written, not autogenerated, same convention as every prior migration
in this repository; `migrations/env.py` keeps `target_metadata = None`.

Purely additive: one new table. No existing column, table, or constraint
is modified or removed.

Revision ID: a204a94ccd49
Revises: 48e9e76153ca
Create Date: 2026-09-11

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a204a94ccd49"
down_revision: str | None = "48e9e76153ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_GRAPH_PROJECTION_JOB_STATUSES = ("queued", "running", "succeeded", "failed", "deferred")


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "graph_projection_jobs",
        sa.Column("projection_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("case_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("evidence_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("observation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        # Sanitized only -- never a raw driver exception string, Cypher
        # text, or stack trace. See `app/modules/graph/errors.py`.
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("observation_id", name="uq_graph_projection_jobs_observation_id"),
        sa.CheckConstraint(
            _check_in("status", _GRAPH_PROJECTION_JOB_STATUSES),
            name="ck_graph_projection_jobs_status",
        ),
    )
    # Supports the projector's claim query: "queued, or running with an
    # expired lease" scoped by status/lease_expires_at.
    op.create_index(
        "ix_graph_projection_jobs_status_lease",
        "graph_projection_jobs",
        ["status", "lease_expires_at"],
    )
    # Supports the case-scoped read endpoint and case-isolation checks.
    op.create_index("ix_graph_projection_jobs_case_id", "graph_projection_jobs", ["case_id"])


def downgrade() -> None:
    op.drop_index("ix_graph_projection_jobs_case_id", table_name="graph_projection_jobs")
    op.drop_index("ix_graph_projection_jobs_status_lease", table_name="graph_projection_jobs")
    op.drop_table("graph_projection_jobs")
