"""structured source type routing

Widens the `source_type` check constraints on `evidence_records` and
`worker_jobs` to accept the two new, additive `SourceType` values added in
Phase 2.3 (`structured_tabular`, `structured_json` -- see
`app/contracts/evidence.py` and `docs/architecture/evidence-lifecycle.md`).
Purely additive: every value the original constraints accepted is still
accepted; only two new values are added.

Hand-written, not autogenerated -- mirrors
`f2086e1e89f6_evidence_lifecycle_foundation.py`'s convention exactly (this
migration only widens two `CHECK` constraints it originally created; no
table/column shape changes).

Revision ID: af5b05e61b08
Revises: 102857ca8d1d
Create Date: 2026-09-11

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af5b05e61b08"
down_revision: str | None = "102857ca8d1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_SOURCE_TYPES = ("document", "cdr", "financial", "video", "image", "audio", "chat", "other")
_NEW_SOURCE_TYPES = (
    "document",
    "cdr",
    "financial",
    "video",
    "image",
    "audio",
    "chat",
    "structured_tabular",
    "structured_json",
    "other",
)


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.drop_constraint("ck_evidence_records_source_type", "evidence_records", type_="check")
    op.create_check_constraint(
        "ck_evidence_records_source_type",
        "evidence_records",
        _check_in("source_type", _NEW_SOURCE_TYPES),
    )
    op.drop_constraint("ck_worker_jobs_source_type", "worker_jobs", type_="check")
    op.create_check_constraint(
        "ck_worker_jobs_source_type", "worker_jobs", _check_in("source_type", _NEW_SOURCE_TYPES)
    )


def downgrade() -> None:
    op.drop_constraint("ck_worker_jobs_source_type", "worker_jobs", type_="check")
    op.create_check_constraint(
        "ck_worker_jobs_source_type", "worker_jobs", _check_in("source_type", _OLD_SOURCE_TYPES)
    )
    op.drop_constraint("ck_evidence_records_source_type", "evidence_records", type_="check")
    op.create_check_constraint(
        "ck_evidence_records_source_type",
        "evidence_records",
        _check_in("source_type", _OLD_SOURCE_TYPES),
    )
