"""observation batch ingestion

Phase 3 (Nipun): adds the durable persistence a worker's partial,
provenance-rich `ObservationBatchSubmissionV1` micro-batches need --
`observation_batches` (one immutable receipt per accepted batch),
`observation_transformations` (durable transformation provenance), and
`worker_progress_events` (an ordered, append-only progress-event history) --
plus the "equivalent durable linkage" `worker_observations` change this
phase's design chose over a second, parallel observations table: `result_id`
becomes nullable and a new nullable `observation_batch_id` is added, with a
`CHECK` constraint enforcing that exactly one of the two is ever set. See
`docs/architecture/phase-3-decisions.md` for the full reasoning.

Both `evidence_lifecycle`'s own `worker_results`-linked observations (Phase
2.1) and this phase's `observation_batches`-linked observations land in the
same `worker_observations` table -- so `app/modules/graph/outbox_repository
.get_observation` (which reads that table by `observation_id` alone) and
`count_observations_for_job` need no change at all to see both.

Hand-written, not autogenerated, same convention as every prior migration in
this repository; `migrations/env.py` keeps `target_metadata = None`.

This migration is purely additive except for the two `worker_observations`
column changes noted above (a widening `NULL` relaxation plus one new
nullable column) -- no existing row's `result_id` value is touched, and no
prior migration file is modified.

Revision ID: c1c9c1c9d9f1
Revises: ed593db47d8c
Create Date: 2026-09-12

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1c9c1c9d9f1"
down_revision: str | None = "ed593db47d8c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_TRANSFORMATION_STATUSES = ("succeeded", "partial", "failed")


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "observation_batches",
        sa.Column("observation_batch_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("worker_jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "evidence_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("evidence_records.evidence_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("batch_id", sa.Text(), nullable=False),
        sa.Column("batch_sequence", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("is_final_batch", sa.Boolean(), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("job_id", "batch_id", name="uq_observation_batches_job_batch_id"),
        sa.UniqueConstraint(
            "job_id", "idempotency_key", name="uq_observation_batches_job_idempotency_key"
        ),
        sa.CheckConstraint("batch_sequence >= 0", name="ck_observation_batches_sequence_positive"),
        sa.CheckConstraint(
            "observation_count >= 0", name="ck_observation_batches_observation_count_positive"
        ),
        sa.CheckConstraint(
            "payload_hash ~ '^[0-9a-f]{64}$'", name="ck_observation_batches_payload_hash_format"
        ),
    )
    op.create_index("ix_observation_batches_case_id", "observation_batches", ["case_id"])
    op.create_index("ix_observation_batches_evidence_id", "observation_batches", ["evidence_id"])
    # Supports "ordered micro-batches" reads: all batches for a job, oldest-sequence-first.
    op.create_index(
        "ix_observation_batches_job_id_sequence",
        "observation_batches",
        ["job_id", "batch_sequence"],
    )

    # --- worker_observations: equivalent durable linkage for batch-sourced rows ---
    op.alter_column("worker_observations", "result_id", nullable=True)
    op.add_column(
        "worker_observations",
        sa.Column(
            "observation_batch_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("observation_batches.observation_batch_id", ondelete="CASCADE"),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "ck_worker_observations_exactly_one_source",
        "worker_observations",
        "(result_id IS NULL) <> (observation_batch_id IS NULL)",
    )
    op.create_index(
        "ix_worker_observations_observation_batch_id",
        "worker_observations",
        ["observation_batch_id"],
    )

    op.create_table(
        "observation_transformations",
        sa.Column("transformation_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "observation_batch_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("observation_batches.observation_batch_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("worker_jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "evidence_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("evidence_records.evidence_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("step_name", sa.Text(), nullable=False),
        # Sanitized only -- the full `TransformationProvenanceV1` payload
        # (never raw document text/media bytes/credentials/stderr/local
        # filesystem paths -- enforced by the contract's own validator).
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("canonical_payload", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint(
            "observation_batch_id", "ordinal", name="uq_observation_transformations_batch_ordinal"
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_observation_transformations_ordinal_positive"),
        sa.CheckConstraint(
            _check_in("status", _TRANSFORMATION_STATUSES),
            name="ck_observation_transformations_status",
        ),
    )
    op.create_index(
        "ix_observation_transformations_job_id", "observation_transformations", ["job_id"]
    )
    op.create_index(
        "ix_observation_transformations_case_id", "observation_transformations", ["case_id"]
    )
    op.create_index(
        "ix_observation_transformations_evidence_id",
        "observation_transformations",
        ["evidence_id"],
    )

    op.create_table(
        "worker_progress_events",
        sa.Column("progress_event_id", postgresql.UUID(as_uuid=True), primary_key=True),
        # Globally monotonic, server-assigned -- gives a stable, race-free
        # total order across concurrent inserts; carries no other meaning
        # (not per-job, just a tiebreaker/ordering column).
        sa.Column("ordinal", sa.BigInteger(), nullable=False),
        sa.Column(
            "observation_batch_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("observation_batches.observation_batch_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("worker_jobs.job_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "evidence_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("evidence_records.evidence_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("units_total", sa.Integer(), nullable=True),
        sa.Column("units_completed", sa.Integer(), nullable=False),
        sa.Column("observations_emitted", sa.Integer(), nullable=False),
        sa.Column("batch_sequence", sa.Integer(), nullable=False),
        sa.Column("message_code", sa.Text(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("ordinal", name="uq_worker_progress_events_ordinal"),
        sa.CheckConstraint(
            "units_completed >= 0", name="ck_worker_progress_events_units_completed_positive"
        ),
        sa.CheckConstraint(
            "observations_emitted >= 0",
            name="ck_worker_progress_events_observations_emitted_positive",
        ),
        sa.CheckConstraint(
            "batch_sequence >= 0", name="ck_worker_progress_events_batch_sequence_positive"
        ),
        sa.CheckConstraint("attempt >= 1", name="ck_worker_progress_events_attempt_positive"),
    )
    # A `BIGSERIAL`-equivalent: an auto-incrementing identity backing `ordinal`.
    op.execute(
        "CREATE SEQUENCE worker_progress_events_ordinal_seq OWNED BY worker_progress_events.ordinal"
    )
    op.execute(
        "ALTER TABLE worker_progress_events ALTER COLUMN ordinal "
        "SET DEFAULT nextval('worker_progress_events_ordinal_seq')"
    )
    op.create_index(
        "ix_worker_progress_events_job_id_ordinal",
        "worker_progress_events",
        ["job_id", "ordinal"],
    )
    op.create_index(
        "ix_worker_progress_events_observation_batch_id",
        "worker_progress_events",
        ["observation_batch_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_worker_progress_events_observation_batch_id", table_name="worker_progress_events"
    )
    op.drop_index("ix_worker_progress_events_job_id_ordinal", table_name="worker_progress_events")
    op.execute("DROP SEQUENCE IF EXISTS worker_progress_events_ordinal_seq")
    op.drop_table("worker_progress_events")

    op.drop_index(
        "ix_observation_transformations_evidence_id", table_name="observation_transformations"
    )
    op.drop_index(
        "ix_observation_transformations_case_id", table_name="observation_transformations"
    )
    op.drop_index("ix_observation_transformations_job_id", table_name="observation_transformations")
    op.drop_table("observation_transformations")

    op.drop_index("ix_worker_observations_observation_batch_id", table_name="worker_observations")
    op.drop_constraint(
        "ck_worker_observations_exactly_one_source", "worker_observations", type_="check"
    )
    op.drop_column("worker_observations", "observation_batch_id")
    op.alter_column("worker_observations", "result_id", nullable=False)

    op.drop_index("ix_observation_batches_job_id_sequence", table_name="observation_batches")
    op.drop_index("ix_observation_batches_evidence_id", table_name="observation_batches")
    op.drop_index("ix_observation_batches_case_id", table_name="observation_batches")
    op.drop_table("observation_batches")
