"""worker job retry limits

Aditya Phase 3 (Secure Worker Submission, Case-Scoped Claims, Lease/
Heartbeat Control, Retry Limits, and Audit Events): closes the "no
max-attempt cutoff on job claiming" gap `docs/architecture/
worker-job-lifecycle.md`'s "Lease and retry policy" section has documented
as unimplemented since Phase 2.1 (it even named the exact fix: "adding
`AND attempt < :max_attempts`" to the claim eligibility query).

Adds a nullable-never, `NOT NULL` `worker_jobs.max_attempts` column,
mirroring `graph_projection_jobs.max_attempts`'s exact, already-reviewed
pattern (Shreshtha Phase 2, `a204a94ccd49_graph_projection_jobs.py`) rather
than inventing a second retry-limit shape: a job whose lease keeps expiring
is reclaimed (and `attempt` incremented) only while `attempt < max_attempts`;
once exhausted, `EvidenceLifecycleRepository.sweep_retry_exhausted_jobs`
(called at the start of every `claim_job` attempt, the same "opportunistic
sweep on every claim call" convention `graph.outbox_repository.claim_batch`
already established) transitions the job durably to `failed` with a safe,
synthetic terminal `WorkerResultV1` (`error.code="retry_exhausted"`) — never
silently dropped, never left permanently ambiguous between "still retryable"
and "gave up."

Backfills every pre-existing `worker_jobs` row to the same default the
application layer uses (`Settings.worker_job_max_attempts`, default `5`) via
`server_default` — a job claimed before this migration is not retroactively
penalized; it simply starts being bounded going forward, exactly like
`48e9e76153ca`'s migration note for `claimed_by_worker_id` handled the
equivalent "pre-existing row, new column" case.

Hand-written, not autogenerated, same convention as every prior migration in
this repository; `app/modules/evidence_lifecycle/repository.py` defines the
matching SQLAlchemy Core `Table` column; `migrations/env.py` keeps
`target_metadata = None`.

Purely additive: one new column, one new check constraint. No existing
column, table, or constraint is modified or removed.

Revision ID: d3f1a6c9b8e2
Revises: c1c9c1c9d9f1
Create Date: 2026-09-12

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3f1a6c9b8e2"
down_revision: str | None = "c1c9c1c9d9f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Matches `Settings.worker_job_max_attempts`'s own default -- see
#: `app/core/config.py`. Kept as a plain literal here (not imported) since
#: migrations must never depend on application code that could change out
#: from under an already-applied revision.
_DEFAULT_MAX_ATTEMPTS = "5"


def upgrade() -> None:
    op.add_column(
        "worker_jobs",
        sa.Column(
            "max_attempts",
            sa.Integer(),
            nullable=False,
            server_default=_DEFAULT_MAX_ATTEMPTS,
        ),
    )
    op.create_check_constraint(
        "ck_worker_jobs_max_attempts_positive", "worker_jobs", "max_attempts >= 1"
    )
    # Supports the claim eligibility query's added `attempt < max_attempts`
    # predicate and the retry-exhaustion sweep's `attempt >= max_attempts`
    # predicate, both evaluated on every single claim attempt.
    op.create_index(
        "ix_worker_jobs_status_attempt_max_attempts",
        "worker_jobs",
        ["status", "attempt", "max_attempts"],
    )


def downgrade() -> None:
    op.drop_index("ix_worker_jobs_status_attempt_max_attempts", table_name="worker_jobs")
    op.drop_constraint("ck_worker_jobs_max_attempts_positive", "worker_jobs", type_="check")
    op.drop_column("worker_jobs", "max_attempts")
