"""communication source type routing

Widens the `source_type` check constraints on `evidence_records` and
`worker_jobs` to accept five new, additive `SourceType` values
(`audio_transcript`, `audio_diarization`, `whatsapp_chat`, `telegram_chat`,
`instagram_chat` -- see `app/contracts/evidence.py` and
`docs/architecture/evidence-lifecycle.md`) that make
`communication_processing`'s five previously-upload-unreachable processor
profiles (`transcript_import_v1`, `diarization_import_v1`,
`whatsapp_export_v1`, `telegram_export_v1`, `instagram_export_v1`) real,
server-routable source types for the first time. Purely additive: every
value the constraints already accepted (including Phase 2.3's
`structured_tabular`/`structured_json`) is still accepted; only five new
values are added.

Hand-written, not autogenerated -- mirrors
`af5b05e61b08_structured_source_type_routing.py`'s convention exactly
(widens the same two `CHECK` constraints again; no table/column shape
changes).

Revision ID: ed593db47d8c
Revises: a204a94ccd49
Create Date: 2026-09-11

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed593db47d8c"
down_revision: str | None = "a204a94ccd49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_SOURCE_TYPES = (
    "document",
    "cdr",
    "financial",
    "video",
    "image",
    "audio",
    "chat",
    "structured_tabular",
    "structured_json",
    "other",
)
_NEW_SOURCE_TYPES = (
    "document",
    "cdr",
    "financial",
    "video",
    "image",
    "audio",
    "chat",
    "structured_tabular",
    "structured_json",
    "audio_transcript",
    "audio_diarization",
    "whatsapp_chat",
    "telegram_chat",
    "instagram_chat",
    "other",
)


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.drop_constraint("ck_evidence_records_source_type", "evidence_records", type_="check")
    op.create_check_constraint(
        "ck_evidence_records_source_type",
        "evidence_records",
        _check_in("source_type", _NEW_SOURCE_TYPES),
    )
    op.drop_constraint("ck_worker_jobs_source_type", "worker_jobs", type_="check")
    op.create_check_constraint(
        "ck_worker_jobs_source_type", "worker_jobs", _check_in("source_type", _NEW_SOURCE_TYPES)
    )


def downgrade() -> None:
    op.drop_constraint("ck_worker_jobs_source_type", "worker_jobs", type_="check")
    op.create_check_constraint(
        "ck_worker_jobs_source_type", "worker_jobs", _check_in("source_type", _OLD_SOURCE_TYPES)
    )
    op.drop_constraint("ck_evidence_records_source_type", "evidence_records", type_="check")
    op.create_check_constraint(
        "ck_evidence_records_source_type",
        "evidence_records",
        _check_in("source_type", _OLD_SOURCE_TYPES),
    )
