"""evidence lifecycle foundation

Adds the two Phase 2 evidence-lifecycle tables: `evidence_records`
(persisted `EvidenceRecordV1` metadata) and `worker_jobs` (persisted durable
`WorkerJobV1` records). See `docs/architecture/evidence-lifecycle.md`.

Hand-written, not autogenerated: `migrations/env.py` keeps
`target_metadata = None` (Nipun's baseline decision, unchanged).
`app/modules/evidence_lifecycle/repository.py` defines its own SQLAlchemy
Core `Table` objects matching these columns for querying, rather than
adding a project-wide declarative ORM base -- mirrors
`7e8499f34f29_access_control_foundation.py`'s convention exactly.

Revision ID: f2086e1e89f6
Revises: 7e8499f34f29
Create Date: 2026-09-11

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f2086e1e89f6"
down_revision: str | None = "7e8499f34f29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_SOURCE_TYPES = ("document", "cdr", "financial", "video", "image", "audio", "chat", "other")
_EVIDENCE_CLASSIFICATIONS = ("unclassified", "restricted", "confidential", "secret")
_EVIDENCE_PROCESSING_STATUSES = ("uploaded", "queued", "processing", "processed", "failed")
_WORKER_STATUSES = ("queued", "running", "succeeded", "failed", "deferred", "cancelled")


def _check_in(column: str, values: tuple[str, ...]) -> str:
    quoted = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({quoted})"


def upgrade() -> None:
    op.create_table(
        "evidence_records",
        sa.Column("evidence_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("object_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column(
            "uploaded_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.user_id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parser_profile", sa.Text(), nullable=True),
        sa.Column("processing_status", sa.Text(), nullable=False),
        sa.Column("upload_idempotency_key", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("object_uri", name="uq_evidence_records_object_uri"),
        sa.CheckConstraint(
            _check_in("source_type", _SOURCE_TYPES), name="ck_evidence_records_source_type"
        ),
        sa.CheckConstraint(
            _check_in("classification", _EVIDENCE_CLASSIFICATIONS),
            name="ck_evidence_records_classification",
        ),
        sa.CheckConstraint(
            _check_in("processing_status", _EVIDENCE_PROCESSING_STATUSES),
            name="ck_evidence_records_processing_status",
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_evidence_records_sha256_format"),
    )
    op.create_index("ix_evidence_records_case_id", "evidence_records", ["case_id"])
    op.create_index("ix_evidence_records_uploaded_by", "evidence_records", ["uploaded_by"])
    # Partial unique index: only enforced when a client actually supplied an
    # `Idempotency-Key`. Two uploads in the same case with no key are
    # unrelated requests, never compared against each other.
    op.create_index(
        "uq_evidence_records_case_idempotency_key",
        "evidence_records",
        ["case_id", "upload_idempotency_key"],
        unique=True,
        postgresql_where=sa.text("upload_idempotency_key IS NOT NULL"),
    )

    op.create_table(
        "worker_jobs",
        sa.Column("job_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "case_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cases.case_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "evidence_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("evidence_records.evidence_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("source_type", sa.Text(), nullable=False),
        sa.Column("processor_name", sa.Text(), nullable=False),
        sa.Column("processor_version", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("input_object_uri", sa.Text(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column("last_error_retryable", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("idempotency_key", name="uq_worker_jobs_idempotency_key"),
        sa.CheckConstraint(
            _check_in("source_type", _SOURCE_TYPES), name="ck_worker_jobs_source_type"
        ),
        sa.CheckConstraint(_check_in("status", _WORKER_STATUSES), name="ck_worker_jobs_status"),
        sa.CheckConstraint("attempt >= 1", name="ck_worker_jobs_attempt_positive"),
    )
    op.create_index("ix_worker_jobs_case_id", "worker_jobs", ["case_id"])
    op.create_index("ix_worker_jobs_evidence_id", "worker_jobs", ["evidence_id"])


def downgrade() -> None:
    op.drop_table("worker_jobs")
    op.drop_table("evidence_records")
