"""Phase 6 throughput and first-useful-output benchmark.

Runs the real ingestion pipeline (HTTP upload -> worker parse/normalize ->
fragment commit -> UTXO graph build -> deterministic findings/features ->
optional ML findings) through the same FastAPI app and worker code the
service runs in production, and times each stage separately. No stage is
mocked or estimated: every number this script prints came from an actual
run on this host.

Two scales:

  * ``--scale 100k`` replays the existing generator-v2 fixture at
    ``datasets/phase5a_100k/ingestion_rows.ndjson`` (already generated by
    ``make dataset``). This is the labelled scenario fixture, unmodified.
  * ``--scale 1m`` (or an explicit ``--rows N``) generates a lightweight
    synthetic linear-chain NDJSON file on the fly. It is deliberately not
    the scenario generator: at this row count the goal is pipeline
    throughput, not detection scenarios, and the scenario generator has
    no size parameter. Every row is schema-valid and is normalized,
    quarantine-checked, and committed exactly like real data.

Stage attribution is honest about what the code actually separates:

  * ``upload_sec`` -- time inside the POST /imports call (hash-while-write
    + immutable publish + DB job row). Wall clock around the HTTP call.
  * ``source_verification_and_parse_commit_sec`` -- worker source-hash
    reverification, plus the parse/normalize/quarantine/fragment-commit
    loop. This is *not* further split because the production code does not
    split it either: ``ingest_source`` runs one batch loop.
  * ``graph_build_sec`` -- ``build_graph_snapshot``, isolated by wrapping
    the exact symbol ``app.engine.ingestion.pipeline`` calls (no production
    code was changed to get this number).
  * ``deterministic_findings_and_features_sec`` -- ``materialize_findings``.
    Phase 4.1 features and deterministic findings are computed in the same
    function in this codebase; reporting them as two numbers would invent a
    split that does not exist in the source.
  * ``ml_findings_sec`` -- the optional unsupervised anomaly stack, if the
    `ml` extra is installed and enabled.

"first useful output" and "first ranked lead" are measured from the moment
the upload HTTP call returns (evidence durably stored, job queued) to graph
completion and to deterministic-findings completion respectively -- this
pipeline builds the graph once after every batch is ingested, not
incrementally per batch, so "first" here honestly means "only", and that is
called out in the printed report rather than implied otherwise.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import tempfile
import time
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from pathlib import Path

from fastapi.testclient import TestClient
from sqlalchemy.orm import sessionmaker

from app.api import routes
from app.config import Settings
from app.db import Base, get_session, make_engine
from app.engine.ingestion import pipeline as pipeline_module
from app.main import app
from workers import runner

REPO = Path(__file__).resolve().parents[1]


# ---------------------------------------------------------------------------
# Synthetic 1M-scale generator: deliberately simple, deliberately not the
# labelled scenario fixture (which has no size parameter). Every row is a
# valid, schema-conformant transaction: an optional single input spending
# the previous row's output (a linear chain, so the graph builder resolves
# real SPENT_BY edges), one output paying into a small address pool (so a
# handful of addresses become genuinely high-degree nodes for the query
# latency benchmark), amount decreasing by a fixed fee every row.
# ---------------------------------------------------------------------------
def _txid(i: int) -> str:
    return hashlib.sha256(f"phase6-throughput-tx-{i}".encode()).hexdigest()


def generate_synthetic_ndjson(
    path: Path,
    *,
    rows: int,
    address_pool: int,
    seed_amount_sats: int = 5_000_000_000_000,
    fee_sats: int = 500,
    max_chain_hops: int = 5,
) -> None:
    """Many independent short spend chains for pipeline throughput, not scenario detection.

    Two things this deliberately avoids, both found empirically while building
    this benchmark (not fixed here -- fixing them belongs to whichever phase
    owns `app.engine.findings.deterministic`, not the Phase 6 benchmark):

    1. Perfectly periodic address/timing (fixed stride, fixed spacing) hits a
       real duplicate-window collision in `materialize_findings` on data this
       regular; a seeded PRNG for both address choice and inter-arrival time
       avoids it while staying fully deterministic and O(1) memory per row.
    2. One global 2000+-hop spend chain overlaps `detect_peeling_chains`'
       bounded 8-hop windows (`DEFAULT_MAX_PEELING_HOPS`) at nearly every
       possible offset, which also produces duplicate finding keys. Real data,
       and the generator-v2 fixture, never has a single chain that long; many
       independent short chains (capped at `max_chain_hops`) is both more
       representative and avoids the pathological overlap.
    """
    if rows * fee_sats >= seed_amount_sats:
        raise ValueError("seed_amount_sats too small for this many rows at this fee")
    import random

    rng = random.Random(20260929)
    base_time = datetime(2026, 1, 1, tzinfo=UTC)
    path.parent.mkdir(parents=True, exist_ok=True)
    elapsed = 0.0
    written = 0
    with path.open("w", encoding="utf-8") as handle:
        while written < rows:
            chain_len = min(rng.randint(1, max_chain_hops), rows - written)
            amount = seed_amount_sats
            prev_txid: str | None = None
            for _ in range(chain_len):
                txid = _txid(written)
                change = amount - fee_sats
                elapsed += rng.uniform(0.4, 2.0)
                row = {
                    "txid": txid,
                    "network": "bitcoin-mainnet",
                    "timestamp": (base_time + timedelta(seconds=elapsed)).isoformat().replace("+00:00", "Z"),
                    "fee_sats": fee_sats,
                    "inputs": (
                        [{"prev_txid": prev_txid, "prev_vout": 0, "amount_sats": amount}]
                        if prev_txid is not None
                        else []
                    ),
                    "outputs": [
                        {
                            "amount_sats": change,
                            "address": f"synthaddr{rng.randrange(address_pool):06d}",
                            "script_type": "p2wpkh",
                        }
                    ],
                }
                handle.write(json.dumps(row, separators=(",", ":")))
                handle.write("\n")
                prev_txid = txid
                amount = change
                written += 1


@dataclass
class StageTimer:
    label: str
    total_sec: float = 0.0
    calls: int = 0

    def wrap(self, fn):
        def wrapped(*args, **kwargs):
            started = time.perf_counter()
            try:
                return fn(*args, **kwargs)
            finally:
                self.total_sec += time.perf_counter() - started
                self.calls += 1

        return wrapped


@dataclass
class BenchmarkResult:
    scale: str
    source_path: str
    source_bytes: int
    row_width: int
    rows_seen: int = 0
    rows_accepted: int = 0
    rows_quarantined: int = 0
    upload_sec: float = 0.0
    ingest_total_sec: float = 0.0
    graph_build_sec: float = 0.0
    deterministic_findings_sec: float = 0.0
    ml_findings_sec: float = 0.0
    graph_nodes: int = 0
    graph_edges: int = 0
    finding_count: int = 0
    ml_status: str = "unknown"
    peak_evidence_bytes: int = 0
    notes: list[str] = field(default_factory=list)

    @property
    def source_verification_and_parse_commit_sec(self) -> float:
        return max(0.0, self.ingest_total_sec - self.graph_build_sec - self.deterministic_findings_sec - self.ml_findings_sec)

    @property
    def first_useful_output_sec(self) -> float:
        """Upload-complete -> graph committed (this pipeline builds the graph once, not per-batch)."""
        return self.source_verification_and_parse_commit_sec + self.graph_build_sec

    @property
    def first_ranked_lead_sec(self) -> float:
        """Upload-complete -> first deterministic finding committed (findings run right after the graph)."""
        return self.first_useful_output_sec + self.deterministic_findings_sec

    def as_dict(self) -> dict:
        return {
            "scale": self.scale,
            "source_path": self.source_path,
            "source_bytes": self.source_bytes,
            "row_width_columns": self.row_width,
            "rows_seen": self.rows_seen,
            "rows_accepted": self.rows_accepted,
            "rows_quarantined": self.rows_quarantined,
            "upload_sec": round(self.upload_sec, 3),
            "source_verification_and_parse_commit_sec": round(self.source_verification_and_parse_commit_sec, 3),
            "graph_build_sec": round(self.graph_build_sec, 3),
            "deterministic_findings_and_features_sec": round(self.deterministic_findings_sec, 3),
            "ml_findings_sec": round(self.ml_findings_sec, 3),
            "ingest_total_sec": round(self.ingest_total_sec, 3),
            "first_useful_output_sec": round(self.first_useful_output_sec, 3),
            "first_ranked_lead_sec": round(self.first_ranked_lead_sec, 3),
            "rows_per_sec_ingest": round(self.rows_accepted / self.ingest_total_sec, 1) if self.ingest_total_sec else None,
            "graph_nodes": self.graph_nodes,
            "graph_edges": self.graph_edges,
            "finding_count": self.finding_count,
            "ml_status": self.ml_status,
            "notes": self.notes,
        }


def _row_width(path: Path, source_format: str) -> int:
    if source_format == "csv":
        import csv

        with path.open("r", encoding="utf-8-sig", newline="") as handle:
            reader = csv.reader(handle)
            return len(next(reader))
    if source_format == "ndjson":
        with path.open("r", encoding="utf-8-sig") as handle:
            for line in handle:
                if line.strip():
                    return len(json.loads(line))
    return 0


def run_benchmark(*, source_path: Path, scale_label: str, ml_enabled: bool) -> BenchmarkResult:
    source_format = source_path.suffix.lstrip(".")
    source_bytes = source_path.stat().st_size
    row_width = _row_width(source_path, source_format)
    payload = source_path.read_bytes()

    # `/tmp` is tmpfs (RAM-backed) on this host -- writing the evidence root
    # and control DB there would compete with the ingestion process's own
    # heap for the same physical memory instead of using real disk. `var/`
    # is ext4.
    work_root = REPO / "var" / "phase6-tmp"
    work_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="throughput-", dir=work_root) as temp:
        root = Path(temp)
        engine = make_engine(f"sqlite:///{root / 'control.db'}")
        Base.metadata.create_all(engine)
        sessions = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)
        settings = Settings(
            database_url=f"sqlite:///{root / 'control.db'}",
            evidence_root=root / "evidence",
            max_upload_bytes=len(payload) + 1,
            lease_seconds=600,
            event_heartbeat_seconds=5,
            ingestion_batch_records=32768,
            ml_findings_enabled=ml_enabled,
        )

        def override_session():
            with sessions() as session:
                yield session

        old_route_settings, old_worker_settings, old_sessions = routes.settings, runner.settings, runner.SessionLocal
        app.dependency_overrides[get_session] = override_session
        routes.settings, runner.settings, runner.SessionLocal = settings, settings, sessions

        graph_timer = StageTimer("graph_build")
        findings_timer = StageTimer("deterministic_findings")
        ml_timer = StageTimer("ml_findings")
        original_graph_fn = pipeline_module.build_graph_snapshot
        original_findings_fn = pipeline_module.materialize_findings
        original_ml_fn = pipeline_module._materialize_ml_findings
        pipeline_module.build_graph_snapshot = graph_timer.wrap(original_graph_fn)
        pipeline_module.materialize_findings = findings_timer.wrap(original_findings_fn)
        pipeline_module._materialize_ml_findings = ml_timer.wrap(original_ml_fn)

        result = BenchmarkResult(scale=scale_label, source_path=str(source_path), source_bytes=source_bytes, row_width=row_width)
        client = TestClient(app)
        headers = {"X-TraceX-Actor": "phase6-throughput"}
        try:
            case_id = client.post("/v1/cases", headers=headers, json={"name": f"Phase 6 throughput {scale_label}", "synthetic": True}).json()["case_id"]

            upload_started = time.perf_counter()
            upload = client.post(
                f"/v1/cases/{case_id}/imports",
                headers={**headers, "Idempotency-Key": f"phase6-throughput-{scale_label}"},
                files={"file": (source_path.name, payload, "application/x-ndjson" if source_format == "ndjson" else "text/csv")},
            )
            result.upload_sec = time.perf_counter() - upload_started
            upload.raise_for_status()
            job_id = upload.json()["job_id"]

            ingest_started = time.perf_counter()
            processed = runner.process_one("phase6-throughput-worker")
            result.ingest_total_sec = time.perf_counter() - ingest_started
            if not processed:
                raise RuntimeError("worker did not process the benchmark job")

            job = client.get(f"/v1/jobs/{job_id}", headers=headers).json()
            if job["state"] != "completed":
                raise RuntimeError(f"benchmark job did not complete: {job}")
            result.rows_seen = job["rows_seen"]
            result.rows_accepted = job["rows_accepted"]
            result.rows_quarantined = job["rows_quarantined"]

            with sessions() as session:
                from app.models import FindingRecord, GraphSnapshot

                graph = session.query(GraphSnapshot).filter_by(case_id=case_id).one_or_none()
                if graph is None:
                    raise RuntimeError("graph snapshot missing after ingest")
                result.graph_nodes, result.graph_edges = graph.node_count, graph.edge_count
                result.finding_count = session.query(FindingRecord).filter_by(case_id=case_id).count()

            result.graph_build_sec = graph_timer.total_sec
            result.deterministic_findings_sec = findings_timer.total_sec
            result.ml_findings_sec = ml_timer.total_sec
            if not ml_enabled:
                result.ml_status = "disabled_for_this_run"
                result.notes.append("ML findings disabled for this run to isolate deterministic-pipeline throughput.")
            evidence_files = list(settings.evidence_root.rglob("*"))
            result.peak_evidence_bytes = sum(f.stat().st_size for f in evidence_files if f.is_file())
        finally:
            app.dependency_overrides.clear()
            routes.settings, runner.settings, runner.SessionLocal = old_route_settings, old_worker_settings, old_sessions
            pipeline_module.build_graph_snapshot = original_graph_fn
            pipeline_module.materialize_findings = original_findings_fn
            pipeline_module._materialize_ml_findings = original_ml_fn
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scale", choices=["100k", "1m", "custom"], default="100k")
    parser.add_argument("--rows", type=int, default=None, help="row count for --scale custom (or override for 1m)")
    parser.add_argument("--address-pool", type=int, default=None, help="distinct addresses for the synthetic generator")
    parser.add_argument("--with-ml", action="store_true", help="also run the unsupervised anomaly stack (needs the ml extra)")
    parser.add_argument("--output", type=Path, default=None, help="write JSON result here")
    parser.add_argument("--keep-synthetic", type=Path, default=None, help="persist the generated synthetic NDJSON at this path instead of a temp file")
    parser.add_argument("--source", type=Path, default=None, help="benchmark an existing NDJSON file (e.g. scripts/scale_fixture.py output)")
    args = parser.parse_args()

    if args.source is not None:
        source_path = args.source
        scale_label = source_path.stem
    elif args.scale == "100k":
        source_path = REPO / "datasets" / "phase5a_100k" / "ingestion_rows.ndjson"
        if not source_path.exists():
            raise SystemExit(f"missing {source_path} -- run `make dataset` first")
        scale_label = "100k"
    else:
        rows = args.rows or (1_000_000 if args.scale == "1m" else 10_000)
        # ~33 rows/address, matching the 100K synthetic reference point
        # (pool=3000) -- keeps different `--rows` runs comparable instead of
        # silently changing address-reuse density, which independently drives
        # `materialize_findings`' memory/time cost (see docs/phase6.md §1).
        pool = args.address_pool or max(200, rows // 33)
        scale_label = args.scale if args.scale != "custom" else f"custom-{rows}"
        target = args.keep_synthetic or (REPO / "var" / "phase6-tmp" / f"synthetic-{rows}.ndjson")
        print(f"Generating {rows} synthetic rows (address pool {pool}) at {target} ...")
        gen_started = time.perf_counter()
        generate_synthetic_ndjson(target, rows=rows, address_pool=pool)
        print(f"Generation took {time.perf_counter() - gen_started:.2f}s, {target.stat().st_size} bytes")
        source_path = target

    print(f"Running phase6 throughput benchmark: scale={scale_label} source={source_path}")
    result = run_benchmark(source_path=source_path, scale_label=scale_label, ml_enabled=args.with_ml)
    payload = result.as_dict()
    print(json.dumps(payload, indent=2))
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
