"""Shared types for the worker boundary: input payloads and the RawMention shape.

Mirrors `app.modules.structured_processing.models` in spirit (a small,
frozen, dependency-free set of dataclasses used to move data between the
parsing layer and `provenance.mention_to_observation`), but this module is
self-contained — it does not import from `structured_processing`, keeping
the two sibling modules independently buildable and independently owned.

There is no `SourceResolver` here: unlike `structured_processing.worker.
process_job` (which resolves `input_object_uri` to bytes itself), this
module's `process_job(job, input_payload)` receives its already-typed,
role-tagged input directly — the three audio roles and the social-export
payload are the "safe input roles" the task brief requires, and dispatch
happens on which dataclass variant was actually supplied, not on a
resolved file's sniffed content.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal

from pydantic import JsonValue

from app.contracts.common import SourceLocator


@dataclass(frozen=True)
class RawMention:
    """One extracted, unresolved fact, ready to become one `ObservationV1`.

    `event_time` is set only when the source gave an unambiguous absolute
    timestamp (see `social/common.py`'s UTC-normalization policy) — never
    guessed. Transcript/diarization segments never set it: their `start_ms`/
    `end_ms` are offsets relative to the audio file, not calendar time.
    """

    observation_type: str
    text: str
    locator: SourceLocator
    confidence: float
    entity_type_hint: str | None = None
    attributes: dict[str, JsonValue] = field(default_factory=dict)
    event_time: datetime | None = None


@dataclass(frozen=True)
class ProcessorProfile:
    """Versioned metadata identifying which processing logic produced an observation."""

    name: str
    version: str
    description: str
    observation_types: tuple[str, ...]
    confidence_rule: str


@dataclass(frozen=True)
class AudioMetadataInput:
    """role=audio_metadata: local audio bytes plus filename for format routing."""

    filename: str
    data: bytes
    role: Literal["audio_metadata"] = "audio_metadata"


@dataclass(frozen=True)
class TranscriptSegmentInput:
    """One externally-supplied transcript segment (never generated by this module)."""

    start_ms: int
    end_ms: int
    text: str
    language_hint: str | None
    confidence: float
    source_segment_id: str


@dataclass(frozen=True)
class TranscriptImportInput:
    """role=transcript_segments: import of externally-produced ASR output."""

    segments: tuple[TranscriptSegmentInput, ...]
    role: Literal["transcript_segments"] = "transcript_segments"


@dataclass(frozen=True)
class DiarizationSegmentInput:
    """One externally-supplied speaker turn. `speaker_label` is source-local only."""

    start_ms: int
    end_ms: int
    speaker_label: str
    confidence: float
    source_segment_id: str


@dataclass(frozen=True)
class DiarizationImportInput:
    """role=diarization_segments: import of externally-produced diarization output."""

    segments: tuple[DiarizationSegmentInput, ...]
    role: Literal["diarization_segments"] = "diarization_segments"


@dataclass(frozen=True)
class SocialExportInput:
    """role=social_export: raw bytes of one documented local social/chat export format."""

    platform: Literal["whatsapp", "telegram", "instagram", "generic_json"]
    data: bytes
    role: Literal["social_export"] = "social_export"


InputPayload = (
    AudioMetadataInput | TranscriptImportInput | DiarizationImportInput | SocialExportInput
)
